spring:
  application:
    name: service-eureka

server:
  port: 8762

eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
   #进行高可用设置时，将register-with-eureka 设置为true，默认，更改端口即可

  instance:
    hostname: eureka-peer2
    appname: eureka
#  server:
#    enable-self-preservation: false  #关闭自我保护
#    eviction-interval-timer-in-ms: 3000  #清理间隔（单位毫秒）
