spring:
  application:
    name: user-center
 #数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/Library?useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    connectionProperties: druid.stat.mergeSql=true
  zipkin:
    base-url: http://localhost:9000
  sleuth:
    sampler:
      percentage: 1.0



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8010

mybatis:
  #实体类所做包
  type-aliases-package: com.springcloud.use.entity
  #mapper.xml所在位置
  mapper-locations: classpath:mapper/*.xml


