eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

server:
  port: 8002

spring:
  application:
    name: feign-service
  zipkin:
    base-url: http://localhost:9000
  sleuth:
    sampler:
      percentage: 1.0



